eshop/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master/',views.Master,name="master"),
    path('',views.Index,name="index"),

    path('signup',views.signup,name='signup'),
    path('login',views.login,name='login'),
    path('accounts/',include('django.contrib.auth.urls')),


    # add to cart

    path('cart/add/<int:id>',views.cart_add,name="cart_add"),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',views.item_increment,name='item_increment'),
    path('cart/item_decrement/<int:id>/',views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/', views.cart_detail,name='cart_detail'),


    # contact page

    path('contact/',views.contact_page,name="contact_page"),


    # Checkout page
    path('checkout/',views.checkout,name="checkout"),

    # order page
    path('order/',views.your_order,name='order'),

    # Product page
    path('product/',views.Product_page,name='product'),

    # Product detail page
    path('product/<str:id>',views.Product_detail,name="product_detail"),

    # Search page
    path('search/',views.Search,name='search'),

    # Account Page
    path('account/',views.Account,name='account'),

    # Info Page
    path('info/',views.info,name='info')

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

main/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
import datetime

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class Sub_Category(models.Model):
    name = models.CharField(max_length=150)
    # link this model with primary model
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=1000)

    def __str__(self):
        return self.name

class Product(models.Model):
    Availability = (('In Stock','In Stock'),('Out Of Stock','Out Of Stock'))
    Condition = (('New','New'),('Refurbished','Refurbished'))

    # link this model with category model and sub category model
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE,null=True)

    image = models.ImageField(upload_to="ecommerce/pimg")
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    availability = models.CharField(choices=Availability,null=True,max_length=100)
    condition = models.CharField(choices=Condition,null=True,max_length=100)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name



class Usercreateform(UserCreationForm):
    email = forms.EmailField(required=True,label='Email',error_messages={'exits':'This user already Exists'})

    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    def __init__(self, *args, **kwargs):
        super(Usercreateform, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'


    def save(self, commit=True):
        user = super(Usercreateform, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError(self.fields['email'].error_message['exists'])
        return self.cleaned_data['email']

class Contact_us(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.name

class Order1(models.Model):
    image = models.ImageField(upload_to="ecommerce/orders/image")
    product = models.CharField(max_length=1000,default='')
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.CharField(max_length=5)
    total = models.CharField(max_length=1000,default='')
    address = models.TextField()
    phone = models.CharField(max_length=10)
    pincode = models.CharField(max_length=10)
    date = models.DateField(default=datetime.datetime.today)

    def __str__(self):
        return self.product

templates/account.html
{% extends 'master.html' %}
{% block title %}Account{% endblock %}

{% block body %}

<section id="form" style="margin-left:20%; margin-top:20px; margin-bottom:50px;"><!--form-->
	<img src="/static/images/shop/account2.jpeg" alt="" style="height:100px; width:100px; margin-left:35%;"/>
		<div class="container">
			<div class="row">
				<br>
				<br>
				<div class="col-sm-4 col-sm-offset-1">
					<div class="login-form"><!--login form-->
						<h2 style="color:orange;">Profile</h2>
						<label>Name : </label>
						<input class="form-control" style="width:300px;" type="text" value="{{user.username}}" aria-label="readonly input example" readonly>
							<br>
						<label>E-mail :</label>
                            <input class="form-control" style="width:300px;" type="text" value="{{user.email}}" aria-label="readonly input example" readonly>
					</div><!--/login form-->
				</div>


				<div class="col-sm-4" >
					<div class="signup-form"><!--sign up form-->
						<h2 style="color:orange;">Quick Links</h2>
						<br>
						<ul class="nav nav-pills">
							<li><a href="{% url 'password_reset' %}" style="color:grey;" onMouseOver="this.style.color='orange'"
				   				onMouseOut="this.style.color='grey'">Change Password</a></li>

							<li><a href="{% url 'password_reset' %}" style="color:grey;" onMouseOver="this.style.color='orange'"
				   				onMouseOut="this.style.color='grey'">Forgot Password ?</a></li>
						</ul>

						<br>
						<br>

						<ul class="nav nav-pills">
								<li><a href="/cart/cart-detail/" style="color:grey;" onMouseOver="this.style.color='orange'"
				   				onMouseOut="this.style.color='grey'">Cart&nbsp;<span class="badge badge-secondary">{{request.session.cart|length}}</span></a></li>

								<li><a href="/order/" style="color:grey;" onMouseOver="this.style.color='orange'"
				   				onMouseOut="this.style.color='grey'">Your Order</a></li>

								<li><a href="{% url 'logout' %}" style="color:grey;" onMouseOver="this.style.color='orange'"
				   				onMouseOut="this.style.color='grey'">Logout </a></li>
						</ul>
					</div><!--/sign up form-->
				</div>
			</div>
		</div>
	<br>
	<br>
	<a href="{% url 'index' %}" class="btn btn-default acc_btn" style="margin-left:35%; width:120px;">Done</a>
	</section><!--/form-->

{% endblock %}

templates/contact.html
{% extends 'master.html' %}
{% block title %}contact{% endblock %}

{% block body %}
<div id="contact-page" class="container">
    	<div class="bg">
	    	<div class="row">
	    		<div class="col-sm-12">
					<h2 class="title text-center">Contact <strong>Us</strong></h2>
<!--                    to display map on our website-->
					<div id="gmap" class="contact-map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d30267.807861376263!2d73.78714987289779!3d18.507380594653746!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2bfb732af849d%3A0xd4078b48b3fe44f0!2sKothrud%2C%20Pune%2C%20Maharashtra!5e0!3m2!1sen!2sin!4v1672152176840!5m2!1sen!2sin" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>					</div>
				</div>
			</div>
            <br>
    		<div class="row">
	    		<div class="col-sm-8">
	    			<div class="contact-form">
	    				<h2 class="title text-center">Get In Touch With Us</h2>
	    				<div class="status alert alert-success" style="display: none"></div>
				    	<form id="main-contact-form" class="contact-form row" name="contact-form" method="POST">
							{% csrf_token %}
				            <div class="form-group col-md-6">
				                <input type="text" name="name" class="form-control" required="required" placeholder="Name">
				            </div>
				            <div class="form-group col-md-6">
				                <input type="email" name="email" class="form-control" required="required" placeholder="Email">
				            </div>
				            <div class="form-group col-md-12">
				                <input type="text" name="subject" class="form-control" required="required" placeholder="Subject">
				            </div>
				            <div class="form-group col-md-12">
				                <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Your Message Here"></textarea>
				            </div>
				            <div class="form-group col-md-12">
				                <input type="submit" name="submit" class="btn btn-primary pull-right" value="Submit">
				            </div>
				        </form>
	    			</div>
	    		</div>
	    		<div class="col-sm-4">
	    			<div class="contact-info">
	    				<h2 class="title text-center">Contact Info</h2>
	    				<address>
	    					<p>Zudio</p>
							<p>Kothrud,Pune.</p>
							<p>Deccan,Pune</p>
							<p>Mobile: +2346 17 38 93</p>
							<p>Fax: 1-714-252-0026</p>
							<p>Email: shopping@zudio.com</p>
	    				</address>
	    				<div class="social-networks">
	    					<h2 class="title text-center">Social Networking</h2>
							<ul>
								<li>
									<a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="https://twitter.com/i/flow/login"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="https://myaccount.google.com/"><i class="fa fa-google-plus"></i></a>
								</li>
								<li>
									<a href="https://www.google.com/"><i class="fa fa-youtube"></i></a>
								</li>
							</ul>
	    				</div>
	    			</div>
    			</div>
	    	</div>
    	</div>
    </div><!--/#contact-page-->
{% endblock %}

templates/index.html
{% extends 'master.html' %}
{% block title %}Home{% endblock %}

{% block body %}
	<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>

						<div class="carousel-inner">
							<div class="item active">
								<div class="col-sm-6">
									<h1><span>Z</span>udio</h1>
									<br>
									<h2>Cash on Delivery</h2>
									<p></p>
								</div>
								<div class="col-sm-6">
									<img src="/static/images/home/girl1.jpg" class="girl img-responsive" alt="" />
									<img src="/static/images/home/pricing.png"  class="pricing" alt="" />
								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">
									<h1><span>Z</span>udio</h1>
									<br>
									<h2>100% Responsive Design</h2>
									<p></p>
								</div>
								<div class="col-sm-6">
									<img src="/static/images/home/girl2.jpg" class="girl img-responsive" alt="" />
									<img src="/static/images/home/pricing.png"  class="pricing" alt="" />
								</div>
							</div>

							<div class="item">
								<div class="col-sm-6">
									<h1><span>Z</span>udio</h1>
									<br>
									<h2>Free Delivery, Free Return<br> Lowest Price</h2>
									<p></p>
								</div>
								<div class="col-sm-6">
									<img src="/static/images/home/girl3.jpg" class="girl img-responsive" alt="" />
									<img src="/static/images/home/pricing.png" class="pricing" alt="" />
								</div>
							</div>

						</div>

						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>

				</div>
			</div>
		</div>
	</section><!--/slider-->




<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-products-->

							{% for cat in category%}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{cat.id}}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{cat.name}}
										</a>
									</h4>
								</div>
								<div id="{{cat.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											{% for i in cat.sub_category_set.all %}
											<li><a href="/?category={{i.id}}">{{i.name}} </a></li>
											{% endfor %}

										</ul>
									</div>
								</div>
							</div>
							{% endfor %}

						</div><!--category-products-->



						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									{% for i in brand %}
									<li><a href="/?brand={{i.id}}">{{i.name}}</a></li>
									{% endfor %}
								</ul>
							</div>
						</div><!--/brands_products-->


					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Features Items</h2>

						{% for prod in product %}
						<div class="col-sm-4 zoom">
							<div class="product-image-wrapper">
								<div class="single-products">
									<a href="/product/{{prod.id}}">
										<div class="productinfo text-center">
											<img src="{{prod.image}}" alt="" height="250px;"/>
											<h2>{{prod.price}}</h2>
											<p>{{prod.name}}</p>
											<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</a>
								</div>
<!--								<div class="choose">-->
<!--									<ul class="nav nav-pills nav-justified">-->
<!--										<li><a href="/product/{{prod.id}}"><i class="fa fa-plus-square"></i>View Product</a></li>-->
<!--									</ul>-->
<!--								</div>-->
							</div>
						</div>
						{% endfor %}
					</div><!--features_items-->

				</div>
			</div>
			<div class="recommended_items"><!--recommended_items-->
				<h2 class="title text-center">Brands</h2>
					<div class="category-tab"><!--category-tab-->
						<div class="col-sm-12">
							<ul class="nav nav-tabs">
								{% for i in brand %}
								<li><a href="/?brand={{i.id}}">{{i.name}}</a></li>
								{% endfor %}
							</ul>
						</div>
					</div><!--/category-tab-->
			</div>
		</div>
	</section>
{% endblock %}

templates/info.html
{% extends 'master.html' %}
{% block title %}information{% endblock %}

{% block body %}

	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->

							{% for cat in category %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{cat.id}}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{cat.name}}
										</a>
									</h4>
								</div>
								<div id="{{cat.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											{% for i in cat.sub_category_set.all %}
											<li><a href="/product/?category={{i.id}}">{{i.name}} </a></li>
											{% endfor %}
										</ul>
									</div>
								</div>
							</div>
							{% endfor %}
						</div><!--/category-products-->

						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									{% for i in brand %}
									<li><a href="/product/?brand={{i.id}}"> <span class="pull-right">(50)</span>{{i.name}}</a></li>
									{% endfor %}
								</ul>
							</div>
						</div><!--/brands_products-->

					</div>
				</div>

<!-- 				featured items-->
				<div class="col-sm-9 padding-right">
					<div class="features_items">
						<h2 class="title text-center" style="font-size:30px;">Result</h2>
						{% for cat in category %}
						<div class="col-sm-4 zoom">
							<label style="color:orange; font-size:20px;">{{cat.name}}</label>
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo">
											{% for i in cat.sub_category_set.all %}
											<a href="/product/?category={{i.id}}" style="color:grey; font-size:15px;">{{i.name}} </a>
											<br>
											{% endfor %}
										</div>
								</div>
							</div>
						</div>
						{% endfor %}

					</div>
					</div><!--features_items-->
				</div>

			</div>
	</section>

{% endblock %}

templates/product.html
{% extends 'master.html' %}
{% block title %}product{% endblock %}

{% block body %}

	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->

							{% for cat in category %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{cat.id}}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{cat.name}}
										</a>
									</h4>
								</div>
								<div id="{{cat.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											{% for i in cat.sub_category_set.all %}
											<li><a href="/product/?category={{i.id}}">{{i.name}} </a></li>
											{% endfor %}
										</ul>
									</div>
								</div>
							</div>
							{% endfor %}
						</div><!--/category-products-->

						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									{% for i in brand %}
									<li><a href="/product/?brand={{i.id}}"> <span class="pull-right">(50)</span>{{i.name}}</a></li>
									{% endfor %}
								</ul>
							</div>
						</div><!--/brands_products-->

					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Features Items</h2>

						{% for prod in product %}
						<div class="col-sm-4 zoom">
							<div class="product-image-wrapper">
								<div class="single-products">
									<label style="color:orange;">{{prod.brand}}</label>
										<a href="{{prod.id}}">
											<div class="productinfo text-center">
												<img src="/{{prod.image}}" alt="" height="250px;"/>
												<h2>{{prod.price}}</h2>
												<p>{{prod.name}}</p>
												<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
											</div>
										</a>
								</div>
<!--								<div class="choose">-->
<!--									<ul class="nav nav-pills nav-justified">-->
<!--										<li><a href="{{prod.id}}"><i class="fa fa-plus-square"></i>View Product</a></li>-->
<!--									</ul>-->
<!--								</div>-->
							</div>
						</div>
						{% endfor %}
					</div>
					</div><!--features_items-->
				</div>


					<div class="recommended_items"><!--recommended_items-->
						<h2 class="title text-center">recommended items</h2>
						<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">
								<div class="item active">
									{% for i in category %}
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<h2><a href="/info/" style="color:orange;">{{i.name}}</a></h2>
												</div>
											</div>
										</div>
									</div>
									{% endfor %}
								</div>
							</div>
						</div>
					</div>


			</div>
	</section>

{% endblock %}

templates/product_detail.html
{% extends 'master.html' %}
{% block title %}product-detail{% endblock %}

{% block body %}


<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-products-->
							{% for cat in category%}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{cat.id}}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{cat.name}}
										</a>
									</h4>
								</div>
								<div id="{{cat.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											{% for i in cat.sub_category_set.all %}
											<li><a href="/?category={{i.id}}">{{i.name}} </a></li>
											{% endfor %}

										</ul>
									</div>
								</div>
							</div>
							{% endfor %}

						</div><!--category-products-->

						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									{% for i in brand %}
									<li><a href="/?brand={{i.id}}">{{i.name}}</a></li>
									{% endfor %}
								</ul>
							</div>
						</div><!--/brands_products-->
					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">About Product</h2>
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="/{{prod.image}}" alt="" />
							</div>
						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<img src="images/product-details/new.jpg" class="newarrival" alt="" />
								<h2>{{prod.name}}</h2>
								<p>Web ID: {{prod.id}}</p>
								<img src="images/product-details/rating.png" alt="" />
								<span>
									<span>₹&nbsp;{{prod.price}}</span>
									<a href="{% url 'cart_add' prod.id %}" type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</a>
								</span>
								<p><b>Availability:</b>&nbsp;{{prod.availability}}</p>
								<p><b>Condition:</b>&nbsp;{{prod.condition}}</p>
								<p><b>Brand:</b> &nbsp;{{prod.brand}}</p>
								<a href=""><img src="images/product-details/share.png" class="share img-responsive"  alt="" /></a>
							</div><!--/product-information-->
						</div>
					</div><!--/product-details-->

					<div class="category-tab shop-details-tab"><!--category-tab-->
						<div class="col-sm-12">
							<ul class="nav nav-tabs" style="align:centre;">
								<li class="active"><a href="#details" data-toggle="tab">Details</a></li>
								<li><a href="#companyprofile" data-toggle="tab">Company Profile</a></li>
								<li><a href="#payment" data-toggle="tab">Payment</a></li>
								<li><a href="#category" data-toggle="tab">Category</a></li>
								<li><a href="#sub-category" data-toggle="tab">Sub-category</a></li>
							</ul>
						</div>
						<div class="tab-content">
							<div class="tab-pane fade active in" id="details" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<label>Condition :</label>
												<p style="font-size:20px;">{{prod.condition}}</p>
												<br>
												<label>Product Name :</label>
												<p style="font-size:20px;">{{prod.name}}</p>
												<br>
												<label>Availability :</label>
												<p style="font-size:20px;">{{prod.availability}}</p>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="tab-pane fade" id="companyprofile" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<label>Company :</label>
												<p style="font-size:20px;">Zudio</p>
												<br>
												<label>Brand Name :</label>
												<p style="font-size:20px;">{{prod.brand}}</p>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="tab-pane fade" id="payment" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<p style="font-size:20px;">COD Available</p>
												<p style="font-size:20px;">CARD</p>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="tab-pane fade" id="category" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<p style="font-size:20px;">{{prod.category}}</p>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="tab-pane fade" id="sub-category" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<p style="font-size:20px;">{{prod.sub_category}}</p>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div><!--/category-tab-->
				</div>
			</div>
`
<!--			<div class="recommended_items"><--recommended_items-->
<!--				<h2 class="title text-center">recommended items</h2>-->
<!--				<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">-->
<!--					<div class="carousel-inner">-->
<!--						<div class="item active">-->
<!--							{% for i in related %}-->
<!--							<div class="col-sm-3">-->
<!--								<div class="product-image-wrapper">-->
<!--									<div class="single-products">-->
<!--										<div class="productinfo text-center">-->
<!--											<img src="/{{i.image}}" alt="" height="250px;" />-->
<!--											<h2><a href="/?category={{i.id}}" style="color:orange;" >{{i.name}}</a></h2>-->
<!--										</div>-->
<!--									</div>-->
<!--								</div>-->
<!--							</div>-->
<!--							{% endfor %}-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->



					<div class="recommended_items"><!--recommended_items-->
						<h2 class="title text-center">recommended items</h2>
						<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">
								<div class="item active">
									{% for i in related %}
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<a href="/?category={{i.id}}">
														<img src="/{{i.image}}" alt="" height="250px;" />
														<h2 style="color:orange;">{{i.name}}</h2>
													</a>
												</div>
											</div>
										</div>
									</div>
									{% endfor %}
								</div>
							</div>
						</div>
					</div>
		</div>
	</div>
</section>

{% endblock %}